import test from 'node:test';
import assert from 'node:assert/strict';
import {createPresetStore,DEFAULT_PRESETS,normalizePreset,LEGACY_PRESETS_KEY} from '../public/js/pigpen-experience-presets.mjs';
const storage=()=>{const data=new Map();return {getItem:k=>data.get(k)||null,setItem:(k,v)=>data.set(k,v),removeItem:k=>data.delete(k)};};
function backend(){const users=new Map(),markers=new Set();const library=u=>{if(!users.has(u))users.set(u,new Map());return users.get(u);};return {
 async initialize(u,defaults){if(markers.has(u))return;for(const p of defaults)library(u).set(p.id,{...p,revision:1,seeded:true});markers.add(u);},
 async load(u){return structuredClone([...library(u).values()]);},
 async save(u,p,rev){const old=library(u).get(p.id);if((old?.revision||0)!==rev)throw Object.assign(Error('conflict'),{code:'preset-conflict'});const saved={...structuredClone(p),revision:rev+1,seeded:false};library(u).set(p.id,saved);return saved;},
 async remove(u,id,rev){if(library(u).get(id)?.revision!==rev)throw Object.assign(Error('conflict'),{code:'preset-conflict'});library(u).delete(id);}
};}
const value=(name='Mi preset')=>({name,config:{question_types:['marcar_evidencia','texto'],primary_reward:'imagen',extras:['pista','coleccionable'],reward_image:'data:image/png;base64,YQ==',reward_image_alt:'Mi imagen',reward_image_aspect:1.5},structure:{rooms:6,questionsPerRoom:7}});
async function setup(adapter=backend(),local=storage(),uid='a'){const store=createPresetStore({adapter,storage:local});store.setUser(uid);await store.load();return store;}
test('full presets persist across devices; stable IDs and revisions; deleted defaults stay deleted',async()=>{const adapter=backend(),a=await setup(adapter);assert.equal(a.state().presets.length,4);const saved=await a.save(value());const b=await setup(adapter);assert.deepEqual(b.state().presets.find(p=>p.id===saved.id),saved);const updated=await b.save({...value('MI PRESET'),structure:{rooms:2,questionsPerRoom:3}});assert.equal(updated.id,saved.id);assert.equal(updated.revision,2);await b.remove('preset_classic');await b.load();assert.equal(b.state().presets.some(p=>p.id==='preset_classic'),false);assert.equal(b.state().presets.length,4);});
test('conflicting devices preserve draft and reject stale writes/deletes',async()=>{const adapter=backend(),a=await setup(adapter);const first=await a.save(value());const b=await setup(adapter);await a.save(value());await assert.rejects(b.save(value()),{code:'preset-conflict'});assert.equal(b.state().draft.name,'Mi preset');assert.match(b.state().error,/otro dispositivo/);await assert.rejects(b.remove(first.id),{code:'preset-conflict'});await b.load();await b.save(value());assert.equal(b.state().draft,null);});
test('cache, drafts and preferences are private by UID; offline is read-only',async()=>{const adapter=backend(),local=storage();const a=await setup(adapter,local);await a.save(value());let online=false;const store=createPresetStore({adapter,storage:local,online:()=>online});store.setUser('a');await store.load();assert.equal(store.state().presets.length,5);await assert.rejects(store.save(value('Offline')),{code:'offline'});assert.equal(store.state().draft.name,'Offline');await assert.rejects(store.remove('preset_classic'),{code:'offline'});store.setUser('b');assert.equal(store.state().presets.length,0);assert.equal(store.state().draft,null);store.setUser('a');assert.equal(store.state().draft.name,'Offline');online=true;await store.load();assert.equal(store.state().source,'cloud');});
test('pending loads and saves cannot rehydrate another account',async()=>{const adapter=backend();let release;const load=adapter.load;adapter.load=async u=>{await new Promise(r=>release=r);return load(u);};const store=createPresetStore({adapter,storage:storage()});store.setUser('a');const pending=store.load();while(!release)await new Promise(r=>setTimeout(r,0));store.setUser('b');release();await pending;assert.equal(store.state().uid,'b');assert.equal(store.state().presets.length,0);
 adapter.load=load;await store.load();const save=adapter.save;adapter.save=async(...args)=>{await new Promise(r=>release=r);return save(...args);};const saving=store.save(value());await new Promise(r=>setTimeout(r,10));store.setUser('c');release();await assert.rejects(saving,{code:'account-changed'});assert.equal(store.state().presets.length,0);assert.equal(store.state().draft,null);
});
test('explicit import replaces untouched defaults only; retains backup and reports conflicts/invalid data',async()=>{const local=storage(),store=await setup(backend(),local);await store.save(value());local.setItem(LEGACY_PRESETS_KEY,JSON.stringify([{...DEFAULT_PRESETS[0],config:{question_types:['texto'],primary_reward:'simbolos',extras:[]} },value(),value('Antiguo'),{name:'Roto'}]));const result=await store.importLegacy();assert.deepEqual(result,{imported:2,conflicts:['Mi preset'],invalid:['Roto']});assert.ok(local.getItem(LEGACY_PRESETS_KEY));assert.deepEqual(store.state().presets.find(p=>p.id==='preset_classic').config.question_types,['texto']);assert.equal(store.state().presets.find(p=>p.id==='preset_classic').seeded,false);const again=await store.importLegacy();assert.equal(again.imported,0);});
test('validation rejects unknown options, empty types, excessive image/name/structure',()=>{for(const p of [{...value(),name:'x'.repeat(29)},{...value(),config:{question_types:[]}},{...value(),config:{question_types:['not-valid']}},{...value(),structure:{rooms:9,questionsPerRoom:2}},{...value(),config:{...value().config,reward_image:'data:image/png;base64,'+'A'.repeat(350000)}},{...value(),config:{...value().config,reward_image_alt:'x'.repeat(501)}}])assert.throws(()=>normalizePreset(p),{code:'invalid-preset'});});
test('failed cloud writes retain draft; blocked local cache never produces false cloud success',async()=>{const adapter=backend(),store=await setup(adapter);adapter.save=async()=>{throw Error('network unavailable');};await assert.rejects(store.save(value()),/network/);assert.equal(store.state().draft.name,'Mi preset');assert.equal(store.state().presets.length,4);const blocked={getItem(){throw Error('blocked');},setItem(){throw Error('full');}};const b=await setup(backend(),blocked);await b.save(value());assert.equal(b.state().presets.length,5);assert.match(b.state().warning,/copia local/);});
