import assert from 'node:assert/strict';
import test from 'node:test';
import vm from 'node:vm';
import { readFileSync } from 'node:fs';
import { build } from 'esbuild';
import media from '../functions/src/podcaster-media-state.js';
import browserMedia from '../public/podcaster/podcaster-media-state.js';
import { sourceFunctions } from './helpers/snoopy-source.mjs';
const clip = (name, revision=name) => ({ storagePath: `${name}.mp4`, downloadUrl: `https://example.test/${name}.mp4`, selectionRevision: revision, updatedAt: '2026-09-10T10:00:00Z', mimeType: 'video/mp4' });
const session = () => ({ id:'s', activeThreadId:'v1', script:{rows:[{id:'r'}]}, dialogueVideoMap:{r:{...clip('manual'),type:'image',manuallyReplaced:true}}, podcastVideoConfig:{timelineClipsByRowId:{r:{type:'image',startMs:731,trimInMs:200,trimOutMs:3400}}}, threads:[{id:'v1',script:{rows:[{id:'r'}]}}] });
for (const [runtime, api] of [['Functions',media],['browser',browserMedia]]) {
 test(`${runtime}: regeneration replaces a manual image, preserving timeline edits`,()=>{
  const s=session(), ctx=api.captureMediaSelection(s,'r','video','job');
  const out=api.selectSceneMedia(s,'r',{...clip('new'),mediaDurationMs:8000},ctx);
  assert.equal(out.status,'applied'); assert.equal(out.clip.storagePath,'new.mp4');
  assert.equal(out.session.podcastVideoConfig.timelineClipsByRowId.r.type,'video');
  assert.equal(out.session.podcastVideoConfig.timelineClipsByRowId.r.startMs,731);
  assert.equal(out.session.podcastVideoConfig.timelineClipsByRowId.r.trimOutMs,3400);
  assert.equal(s.dialogueVideoMap.r.storagePath,'manual.mp4');
  assert.equal(api.selectSceneMedia(out.session,'r',clip('new'),ctx).unchanged,true);
 });
 test(`${runtime}: later selections and deletion reject late jobs`,()=>{
  const s=session(), ctx=api.captureMediaSelection(s,'r','video','old-job');
  s.dialogueVideoMap.r=clip('later');
  assert.equal(api.selectSceneMedia(s,'r',clip('new'),ctx).reason,'selection-changed');
  s.dialogueVideoMap.r={...clip('manual'),type:'image',manuallyReplaced:true};
  s.dialogueVideoDeletedAtMap={r:'2026-09-10T11:00:00Z'};
  assert.equal(api.selectSceneMedia(s,'r',clip('new'),ctx).reason,'scene-removed');
  s.script.rows=[];
  assert.equal(api.selectSceneMedia(s,'r',clip('new'),ctx).status,'superseded');
 });
 test(`${runtime}: a completed job updates its original inactive version`,()=>{
  const s=session(), ctx=api.captureMediaSelection(s,'r','video','job');
  s.threads[0]={...s, id:'v1',threads:undefined};
  s.activeThreadId='v2'; s.dialogueVideoMap={r:clip('other-version')};
  const out=api.selectSceneMedia(s,'r',clip('new'),ctx);
  assert.equal(out.status,'applied'); assert.equal(out.session.dialogueVideoMap.r.storagePath,'other-version.mp4');
  assert.equal(out.session.threads[0].dialogueVideoMap.r.storagePath,'new.mp4');
  assert.equal(api.selectSceneMedia({...s,id:'other-session'},'r',clip('new'),ctx).status,'superseded');
 });
 test(`${runtime}: metadata, arbitrary positions and source trims survive`,()=>{
  const m=api.mediaMetadata({localMediaCacheKey:'local',sourceType:'manual',mediaDurationMs:8371,updatedAt:{seconds:100,nanoseconds:500000000}});
  assert.equal(m.updatedAt,'1970-01-01T00:01:40.500Z');assert.equal(m.localMediaCacheKey,'local');assert.equal(m.mediaDurationMs,8371);
  for (const startMs of [-500,0,1,731,1000,18379]) {
   const s=api.normalizeDialogueSegment({rowId:'r',localMediaCacheKey:'local',startMs,durationMs:2000,trimInMs:400,trimOutMs:2400});
   assert.equal(s.startMs,startMs); assert.equal(s.trimOutMs,2400); assert.equal(s.localMediaCacheKey,'local');
  }
  assert.equal(api.normalizeDialogueSegment({rowId:'r',audioSrc:'test.wav',durationMs:4000}).trimOutMs,4000);
 });
}
test('the browser distribution exactly matches the canonical build',async()=>{
 const result=await build({entryPoints:['functions/src/podcaster-media-state.js'],bundle:true,format:'esm',platform:'browser',write:false,banner:{js:'// Generated by scripts/build-podcaster-media-state.mjs. Edit functions/src/podcaster-media-state.js.'}});
 assert.equal(readFileSync('public/podcaster/podcaster-media-state.js','utf8'), result.outputFiles[0].text);
});
const commitSource=sourceFunctions(new URL('../public/podcaster/podcaster.js',import.meta.url),['commitSceneMediaSelection','preferNewerLocalMediaEntry']);
function harness({fail=false,cloud=session(),local=session(),activeId='s'}={}) {
 const state={sessions:[local]};let writes=0;let hydrated=false;
 const controller={state:{currentMs:2917,isPlaying:false},getBlobUrl:async()=>{hydrated=true;return 'blob:ready';},sync(){},invalidateRowMediaCache:async()=>true};
 const context=vm.createContext({podcasterMediaState:media,state,resolveCurrentUid:()=> 'u',resolveStorageVideoUrl:u=>u,resolveStorageAudioUrl:u=>u,playbackController:controller,exportPreviewController:controller,doc:()=>({}),firestoreDb:{},serverTimestamp:()=>0,
 runTransaction:async(_,fn)=>fn({get:async()=>({exists:()=>true,data:()=>({ownerId:'u',session:cloud})}),update:(_,data)=>{if(fail)throw new Error('write failed');writes++;cloud=data.session;}}),
 upsertSessionById:(id,fn)=>{state.sessions=state.sessions.map(s=>s.id===id?fn(s):s);return state.sessions.find(s=>s.id===id);},
 window:{},getActiveSession:()=>state.sessions.find(s=>s.id===activeId),getPodcastVideoConfig:s=>s.podcastVideoConfig,podcastVideoState:{activeRowId:''},renderPodcastVideoTimeline(){},syncPodcastVideoStageMedia:async()=>{},});
 vm.runInContext(commitSource,context);
 return {context,state,get writes(){return writes;},get hydrated(){return hydrated;}};
}
test('a failed transaction retains the old local scene and propagates failure',async()=>{
 const h=harness({fail:true}),ctx=media.captureMediaSelection(h.state.sessions[0],'r','video','job');
 await assert.rejects(h.context.commitSceneMediaSelection(ctx,clip('new')),/write failed/);
 assert.equal(h.state.sessions[0].dialogueVideoMap.r.storagePath,'manual.mp4');assert.equal(h.hydrated,true);assert.equal(h.writes,0);
});
test('successful application persists before updating the original session',async()=>{
 const h=harness({activeId:'other'}),ctx=media.captureMediaSelection(h.state.sessions[0],'r','video','job');
 const result=await h.context.commitSceneMediaSelection(ctx,clip('new'));
 assert.equal(result.status,'applied');assert.equal(h.writes,1);assert.equal(h.state.sessions[0].dialogueVideoMap.r.storagePath,'new.mp4');
});
test('generated audio is committed without requiring browser media hydration',async()=>{
 const h=harness({activeId:'other'});
 const ctx=media.captureMediaSelection(h.state.sessions[0],'r','audio','voice-job');
 const result=await h.context.commitSceneMediaSelection(ctx,{
  rowId:'r',storagePath:'podcaster/sessions/s/owners/u/audio/voice.wav',
  downloadUrl:'https://example.test/voice.wav',mimeType:'audio/wav',durationSec:3
 });
 assert.equal(result.status,'applied');
 assert.equal(h.writes,1);
 assert.equal(h.hydrated,false);
 assert.equal(h.state.sessions[0].dialogueAudioMap.r.storagePath,'podcaster/sessions/s/owners/u/audio/voice.wav');
});
for (const [runtime, api] of [['Functions',media],['browser',browserMedia]]) {
 test(`${runtime}: selecting new audio clears its deletion tombstone`,()=>{
  const s=session();
  s.dialogueAudioDeletedAtMap={r:'2026-09-10T11:00:00Z'};
  const context=api.captureMediaSelection(s,'r','audio','replacement-audio');
  const out=api.selectSceneMedia(s,'r',{downloadUrl:'replacement.wav',durationSec:3,updatedAt:'2026-09-10T11:01:00Z'},context);
  assert.equal(out.status,'applied');
  assert.equal(out.session.dialogueAudioDeletedAtMap.r,undefined);
  assert.equal(out.session.dialogueAudioMap.r.downloadUrl,'replacement.wav');
 });
}
test('newer cloud selection prevents local replacement and performs zero writes',async()=>{
 const cloud=session();cloud.dialogueVideoMap.r=clip('newer');const h=harness({cloud});
 const result=await h.context.commitSceneMediaSelection(media.captureMediaSelection(h.state.sessions[0],'r','video','job'),clip('new'));
 assert.equal(result.status,'superseded');assert.equal(h.writes,0);assert.equal(h.state.sessions[0].dialogueVideoMap.r.storagePath,'manual.mp4');
});

test('generated audio gets a persisted segment and preserves its authored start',()=>{
 const s=session(),ctx=media.captureMediaSelection(s,'r','audio','audio-job');
 const out=media.selectSceneMedia(s,'r',{downloadUrl:'voice.wav',durationSec:6,playbackRate:1.5},ctx);
 const segment=out.session.podcastVideoConfig.geminiDialogueTrack.segments[0];
 assert.equal(segment.startMs,731);assert.equal(segment.trimOutMs,6000);assert.equal(segment.durationMs,4000);
 assert.equal(out.session.podcastVideoConfig.geminiDialogueTrack.enabled,true);
 segment.startMs=1731;segment.trimInMs=400;segment.trimOutMs=1600;segment.durationMs=800;segment.endMs=2531;
 const nextContext=media.captureMediaSelection(out.session,'r','audio','audio-job2');
 const next=media.selectSceneMedia(out.session,'r',{downloadUrl:'new-voice.wav',durationSec:12},nextContext);
 const actual=next.session.podcastVideoConfig.geminiDialogueTrack.segments[0];
 assert.equal(actual.startMs,1731);assert.equal(actual.trimOutMs,12000);assert.equal(actual.durationMs,8000);assert.equal(actual.audioSrc,'new-voice.wav');assert.equal(next.clip.playbackRate,1.5);
});

for (const [runtime, api] of [['Functions', media], ['browser', browserMedia]]) {
 test(`${runtime}: imported voice hides scene text, preserves its placement and restores it when replaced`,()=>{
  const s=session();
  s.podcastVideoConfig.timelineOnScreenTextClipsByRowId={r:{rowId:'r',text:'Guion visible',hidden:false,startMs:800}};
  s.podcastVideoConfig.geminiDialogueTrack={enabled:true,segments:[{rowId:'r',startMs:1731,endMs:3731,durationMs:2000,trimInMs:0,trimOutMs:2000,volume:0.35}]};
  s.dialogueAudioMap={r:{model:'gemini',downloadUrl:'old.wav',durationSec:2,playbackRate:1.5}};
  const first=api.selectSceneMedia(s,'r',{model:'uploaded',downloadUrl:'voice.mp3',storagePath:'audio/voice.mp3',durationSec:5},api.captureMediaSelection(s,'r','audio','import'));
  assert.equal(first.status,'applied');
  assert.equal(first.session.podcastVideoConfig.timelineOnScreenTextClipsByRowId.r.hidden,true);
  assert.equal(first.session.podcastVideoConfig.geminiDialogueTrack.segments[0].startMs,1731);
  assert.equal(first.session.podcastVideoConfig.geminiDialogueTrack.segments[0].durationMs,5000);
  assert.equal(first.clip.playbackRate,1);
  assert.equal(first.session.podcastVideoConfig.geminiDialogueTrack.segments[0].volume,0.35);
  const next=api.selectSceneMedia(first.session,'r',{model:'gemini',downloadUrl:'new-voice.wav',durationSec:3},api.captureMediaSelection(first.session,'r','audio','gemini'));
  assert.equal(next.status,'applied');
  assert.equal(next.session.podcastVideoConfig.timelineOnScreenTextClipsByRowId.r.hidden,false);
  assert.equal(next.session.podcastVideoConfig.timelineOnScreenTextClipsByRowId.r.text,'Guion visible');
 });
}

test('a stale full save preserves newer selections and corrects their timeline type',()=>{
 const current=session(),stale=session();current.dialogueVideoMap.r={...clip('fresh'),updatedAt:'2026-09-10T11:00:00Z',type:'video'};
 const out=media.reconcileSessionMedia(current,stale);
 assert.equal(out.dialogueVideoMap.r.storagePath,'fresh.mp4');assert.equal(out.podcastVideoConfig.timelineClipsByRowId.r.type,'video');
});
const workerCommitSource=sourceFunctions(new URL('../functions/src/ai-jobs.js',import.meta.url),['commitGeneratedSceneMedia']);
for(const mode of ['success','cancelled','write-error'])test(`worker retains generated candidate with explicit ${mode} outcome`,async()=>{
 const s=session();let writes=0;
 const context=vm.createContext({mediaState:media,getAdminServices:()=>({admin:{firestore:{FieldValue:{serverTimestamp:()=>0}}},db:{collection:()=>({doc:()=> 'session-ref'}),runTransaction:async fn=>fn({get:async ref=>ref==='job-ref'?{data:()=>({status:mode==='cancelled'?'cancelled':'running'})}:{exists:true,data:()=>({session:s})},update:()=>{if(mode==='write-error')throw new Error('offline');writes++;}})}})});
 vm.runInContext(workerCommitSource,context);
 const out=await context.commitGeneratedSceneMedia({sessionId:'s',input:{selectionContext:media.captureMediaSelection(s,'r','video','job')}},clip('created'),'job-ref');
 assert.equal(out.status,mode==='success'?'applied':mode==='cancelled'?'superseded':'error');
 assert.equal(out.clip.storagePath,'created.mp4');assert.equal(writes,mode==='success'?1:0);
});

test('legacy root-only cloud sessions accept the UI first version without bypassing revisions', async () => {
 const local=session(); const cloud=session();delete cloud.activeThreadId;delete cloud.threads;
 const h=harness({local,cloud});const ctx=media.captureMediaSelection(local,'r','video','legacy-job');
 const out=await h.context.commitSceneMediaSelection(ctx,clip('new'));
 assert.equal(out.status,'applied');assert.equal(h.writes,1);
 assert.equal(out.clip.storagePath,'new.mp4');
 const newer={...cloud,dialogueVideoMap:{r:clip('later')}};
 assert.equal(media.selectSceneMedia(newer,'r',clip('new'),ctx).reason,'selection-changed');
 assert.equal(media.selectSceneMedia({...cloud,script:{rows:[]}},'r',clip('new'),ctx).reason,'scene-removed');
 const versioned={...cloud,activeThreadId:'v2',threads:[{id:'v2'}]};
 assert.equal(media.selectSceneMedia(versioned,'r',clip('new'),ctx).status,'superseded');
});

test('cloud serialization preserves version identities, selections and audio deletion markers', async () => {
 const {buildCloudSessionPayload}=await import('../public/podcaster/podcaster-session-payload.js');
 const s=session();s.dialogueAudioDeletedAtMap={r:'2026-09-10T12:00:00Z'};
 s.threads.push({id:'v2',name:'Version 2',script:{rows:[{id:'other'}]},dialogueVideoMap:{other:clip('other')}});
 const saved=buildCloudSessionPayload(s,{},[],{nowIso:()=> '2026-09-10T12:00:00Z',getDialogueVideoMap:s=>s.dialogueVideoMap||{},getDialogueAudioMap:s=>s.dialogueAudioMap||{},normalizePodcastVideoConfig:x=>x});
 assert.equal(saved.activeThreadId,'v1');assert.equal(saved.threads.length,2);
 assert.equal(saved.threads[0].dialogueVideoMap.r.selectionRevision,'manual');
 assert.equal(saved.threads[1].dialogueVideoMap.other.storagePath,'other.mp4');
 assert.deepEqual(saved.threads[1].script.rows.map(row=>row.id),['other']);
 assert.deepEqual(saved.dialogueAudioDeletedAtMap,s.dialogueAudioDeletedAtMap);
 assert.deepEqual(saved.threads[0].dialogueAudioDeletedAtMap,s.dialogueAudioDeletedAtMap);
});

test('cloud object paths and normalized gs references have the same legacy selection revision',()=>{
 const cloud=session();delete cloud.activeThreadId;delete cloud.threads;
 const stored={storagePath:'videos/scene.mp4',downloadUrl:'https://firebasestorage.googleapis.com/v0/b/bucket.test/o/videos%2Fscene.mp4?alt=media&token=old',updatedAt:{seconds:1789065822,nanoseconds:60000000}};
 cloud.dialogueVideoMap.r=stored;
 const local={...session(),dialogueVideoMap:{r:{...stored,storagePath:'gs://bucket.test/videos/scene.mp4',updatedAt:'2026-09-10T18:43:42.060Z'}}};
 const ctx=media.captureMediaSelection(local,'r','video','new-job');
 assert.equal(media.selectSceneMedia(cloud,'r',clip('new'),ctx).status,'applied');
 assert.equal(media.mediaRevision(stored),media.mediaRevision({...stored,downloadUrl:stored.downloadUrl.replace('token=old','token=new')}));
 assert.notEqual(media.mediaRevision(stored),media.mediaRevision({...stored,storagePath:'gs://other.bucket/videos/scene.mp4'}));
 assert.notEqual(media.mediaRevision(stored),media.mediaRevision({...stored,storagePath:'videos/later.mp4'}));
});
