use_default_settings: true
general:
  debug: false
  instance_name: Charly Research
search:
  formats:
    - json
  safe_search: 1
server:
  limiter: false
  public_instance: false
  image_proxy: false
outgoing:
  request_timeout: 8
  max_request_timeout: 12
  pool_connections: 10
  pool_maxsize: 10
engines:
  - name: google
    disabled: true
  - name: bing
    disabled: false
  - name: duckduckgo
    disabled: false
  - name: crossref
    disabled: false
  - name: arxiv
    disabled: false
