steps:
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-f', 'cloud-run/charly-specialist/Dockerfile', '-t', '${_IMAGE}', '.']
images: ['${_IMAGE}']
substitutions:
  _IMAGE: us-central1-docker.pkg.dev/charly-brown/charly-specialists/runtime:latest
