const {createHash,randomUUID}=require("node:crypto");
const {McpServer}=require("@modelcontextprotocol/sdk/server/mcp.js");
const {StreamableHTTPServerTransport}=require("@modelcontextprotocol/sdk/server/streamableHttp.js");
const z=require("zod/v4");
const {prepareUserImport,publicImport}=require("./user-import.js");
const {normalizeBrowserWorkflow,workflowRisk,confirmationFor}=require("./browser-workflow.js");

function textResult(value){return {content:[{type:"text",text:JSON.stringify(value)}],structuredContent:value};}
function digest(value){return createHash("sha256").update(JSON.stringify(value)).digest("hex");}
function state(value,data={}){return {state:value,...data};}

function createSallyMcpServer({actor,sessions,authorizeSession,moodleApi={available:false}}){
  const server=require("./mcp-runtime.generated.js").instrumentMcpServer(new McpServer({name:"sally-moodle-operator",version:"2.0.0"}), "sally-moodle-operator");
  const sessionId=z.string().min(1).max(120);
  async function itemFor(id){const key=await authorizeSession({actor,params:{id}}),item=sessions.get(key);if(!item?.controller)throw Error("Abre primero Moodle en Sally para crear una sesión de navegador.");item.touched=Date.now();return item;}
  async function locked(item,work){if(item.busy)throw Error("Hay otra operación usando este navegador Moodle.");item.busy=true;try{return await work();}finally{item.busy=false;item.touched=Date.now();}}
  function add(name,description,inputSchema,handler,annotations={readOnlyHint:true,destructiveHint:false,idempotentHint:true}){
    server.registerTool(name,{description,inputSchema,annotations},async args=>textResult(await handler(args)));
  }
  function storeBatch(item,kind,value,targetUrl=""){
    const high=value.some?.(entry=>entry.risk==="high"),confirmationText=high?value.find(entry=>entry.risk==="high")?.confirmationText:"";
    if(high&&value.length!==1)throw Error("Las acciones de alto riesgo deben prepararse una por una.");
    const batch={id:randomUUID(),kind,value,targetUrl,risk:high?"high":"standard",confirmationText,hash:digest(value),createdAt:Date.now(),expiresAt:Date.now()+15*60*1000};
    item.mcpBatches ||= new Map();item.mcpBatches.set(batch.id,batch);return state("awaiting_confirmation",{batchId:batch.id,batchHash:batch.hash,risk:batch.risk,confirmationText,expiresAt:new Date(batch.expiresAt).toISOString(),preview:value});
  }
  add("moodle_session_status","Comprueba la sesión Moodle activa y las capacidades disponibles.",{sessionId},async({sessionId:id})=>{const item=await itemFor(id);return state("completed",{connected:true,busy:Boolean(item.busy),capabilities:await item.controller.availability()});});
  add("moodle_read_course","Lee la estructura y los módulos visibles de un curso.",{sessionId,url:z.string().url(),view:z.enum(["model","target"]).default("target")},async({sessionId:id,url,view})=>{const item=await itemFor(id);return locked(item,async()=>{if(moodleApi.available)try{return state("completed",{transport:"moodle-web-service",course:await moodleApi.readCourse(url)});}catch{}return state("completed",{transport:"playwright",course:await item.controller.inspect({url,courseView:view},actor)});});});
  add("moodle_read_module","Lee un módulo perteneciente al inventario Moodle.",{sessionId,url:z.string().url()},async({sessionId:id,url})=>{const item=await itemFor(id);return locked(item,async()=>state("completed",{module:await item.controller.readModule({url},actor)}));});
  add("moodle_describe_page","Describe la página Moodle y sus controles accesibles sin revelar campos secretos.",{sessionId,url:z.string().url()},async({sessionId:id,url})=>{const item=await itemFor(id);return locked(item,async()=>state("completed",{page:await item.controller.describePage({url},actor)}));});
  add("moodle_discover_capabilities","Devuelve las operaciones certificadas y si el navegador semántico está disponible.",{sessionId},async({sessionId:id})=>{const item=await itemFor(id),capabilities=await item.controller.availability();return state("completed",{...capabilities,browserWorkflow:true,approvalRequired:true,highRiskSingleOperation:true});});
  add("moodle_find_users","Busca usuarios visibles para el administrador Moodle.",{sessionId,query:z.string().min(1).max(200),url:z.string().url().optional()},async({sessionId:id,query,url})=>{const item=await itemFor(id);return locked(item,async()=>{if(moodleApi.available&&url)try{return state("completed",{transport:"moodle-web-service",users:await moodleApi.findUsers(url,query)});}catch{}return state("completed",{transport:"playwright",...(await item.controller.findUsers({query},actor))});});});
  add("moodle_inspect_roles","Lee los roles configurados sin modificarlos.",{sessionId},async({sessionId:id})=>{const item=await itemFor(id);return locked(item,async()=>state("completed",await item.controller.inspectRoles({},actor)));});
  add("moodle_prepare_course_batch","Prepara, sin ejecutar, la creación o actualización de un curso.",{sessionId,targetUrl:z.string().url(),action:z.enum(["create","update"]),course:z.object({courseId:z.string().optional(),categoryId:z.union([z.string(),z.number()]).optional(),fullname:z.string().min(1).max(254),shortname:z.string().min(1).max(100),idnumber:z.string().max(100).optional(),summary:z.string().max(50000).optional()})},async({sessionId:id,targetUrl,action,course})=>{const item=await itemFor(id),op={id:randomUUID(),type:"create_or_update_course",target:targetUrl,intent:`${action==="create"?"Crear":"Actualizar"} curso ${course.fullname}`,payload:{...course,courseId:action==="update"?course.courseId||"":""}};return storeBatch(item,"operations",[op],targetUrl);},{readOnlyHint:false,destructiveHint:false,idempotentHint:false});
  add("moodle_prepare_module_batch","Prepara un módulo Moodle; los campos dependen del formulario visible.",{sessionId,targetUrl:z.string().url(),sectionTitle:z.string().min(1).max(255),activityName:z.string().min(1).max(120),title:z.string().min(1).max(255),fields:z.record(z.string(),z.union([z.string(),z.number(),z.boolean()])).optional()},async({sessionId:id,targetUrl,...payload})=>{const item=await itemFor(id),op={id:randomUUID(),type:"create_moodle_module",target:targetUrl,intent:`Crear ${payload.activityName}: ${payload.title}`,payload};return storeBatch(item,"operations",[op],targetUrl);},{readOnlyHint:false,destructiveHint:false,idempotentHint:false});
  add("moodle_prepare_user_import","Normaliza usuarios, genera el CSV Moodle en memoria y devuelve una vista previa sin contraseñas.",{sessionId,defaultCourse:z.string().max(100).optional(),rows:z.array(z.record(z.string(),z.any())).min(1).max(1000)},async({sessionId:id,defaultCourse,rows})=>{const item=await itemFor(id),prepared=prepareUserImport(rows,{defaultCourse});item.secureImports ||= new Map();item.secureImports.set(prepared.id,prepared);return state(prepared.blocked?"needs_user_input":"awaiting_confirmation",publicImport(prepared));},{readOnlyHint:false,destructiveHint:false,idempotentHint:false});
  add("moodle_prepare_meta_link","Prepara un enlace de matriculación entre un curso origen y un metacurso destino.",{sessionId,targetUrl:z.string().url(),sourceCourseId:z.string().regex(/^\d+$/),targetCourseId:z.string().regex(/^\d+$/)},async({sessionId:id,targetUrl,sourceCourseId,targetCourseId})=>{if(sourceCourseId===targetCourseId)throw Error("El curso origen y destino deben ser diferentes.");const item=await itemFor(id),op={id:randomUUID(),type:"create_meta_link",target:targetUrl,intent:`Enlazar curso ${sourceCourseId} con metacurso ${targetCourseId}`,payload:{sourceCourseId,targetCourseId}};return storeBatch(item,"operations",[op],targetUrl);},{readOnlyHint:false,destructiveHint:false,idempotentHint:false});
  const locator=z.object({by:z.enum(["role","label","text","placeholder","title"]),role:z.string().max(40).optional(),name:z.string().min(1).max(300),exact:z.boolean().optional()});
  const workflowStep=z.object({action:z.enum(["goto","click","fill","select","check","uncheck","upload","wait","assert"]),url:z.string().url().optional(),locator:locator.optional(),value:z.string().max(50000).optional(),expected:z.string().max(1000).optional(),milliseconds:z.number().min(100).max(5000).optional()});
  add("moodle_prepare_browser_workflow","Prepara un flujo Playwright semántico para una función Moodle sin adaptador especializado.",{sessionId,targetUrl:z.string().url(),intent:z.string().min(1).max(1000),risk:z.enum(["standard","high"]).default("standard"),steps:z.array(workflowStep).min(1).max(40)},async({sessionId:id,targetUrl,intent,risk,steps})=>{const item=await itemFor(id),payload=normalizeBrowserWorkflow({steps,risk},targetUrl),actualRisk=workflowRisk({risk,intent,steps}),op={id:randomUUID(),type:"browser_workflow",target:targetUrl,intent,risk:actualRisk,...(actualRisk==="high"?{confirmationText:confirmationFor(intent)}:{}),payload};return storeBatch(item,"operations",[op],targetUrl);},{readOnlyHint:false,destructiveHint:true,idempotentHint:false});
  add("moodle_execute_approved_batch","Ejecuta un lote preparado cuyo hash fue confirmado explícitamente.",{sessionId,batchId:z.string().uuid().optional(),importId:z.string().uuid().optional(),batchHash:z.string().regex(/^[a-f0-9]{64}$/),confirm:z.literal(true),confirmationText:z.string().max(300).optional()},async({sessionId:id,batchId,importId,batchHash,confirmationText})=>{const item=await itemFor(id);
    if(importId){const value=item.secureImports?.get(importId);if(!value||value.expiresAt<Date.now())throw Error("La importación expiró. Prepara nuevamente el CSV.");if(value.blocked)throw Error("Corrige las filas bloqueadas antes de continuar.");if(value.hash!==batchHash)throw Error("El CSV cambió y requiere una nueva confirmación.");item.secureImports.delete(importId);try{return locked(item,async()=>state("completed",{result:await item.controller.importUsersCsv({csv:value.csv},actor)}));}finally{value.csv="";for(const row of value.preview)delete row.password;}}
    const batch=item.mcpBatches?.get(batchId);if(!batch||batch.expiresAt<Date.now())throw Error("El lote expiró. Prepáralo nuevamente.");if(batch.hash!==batchHash)throw Error("El lote cambió y requiere una nueva confirmación.");if(batch.risk==="high"&&confirmationText!==batch.confirmationText)throw Error(`Escribe exactamente \"${batch.confirmationText}\" para ejecutar esta acción.`);item.mcpBatches.delete(batch.id);return locked(item,async()=>{await item.controller.approve({plan:batch.value},actor);if(moodleApi.available&&batch.value.every(op=>op.type==="create_or_update_course")){const results=[];for(const operation of batch.value)results.push(await moodleApi.executeCourse(batch.targetUrl,operation));return state("completed",{transport:"moodle-web-service",results});}const result=await item.controller.execute({plan:batch.value,targetUrl:batch.targetUrl},actor);return state(result.state,{transport:"playwright",...result});});
  },{readOnlyHint:false,destructiveHint:false,idempotentHint:false});
  add("moodle_verify_batch","Vuelve a leer el curso para verificar el resultado de un lote.",{sessionId,url:z.string().url()},async({sessionId:id,url})=>{const item=await itemFor(id);return locked(item,async()=>state("completed",{course:await item.controller.inspect({url,courseView:"target",verify:true},actor)}));});
  return server;
}

function registerSallyMcpRoute({app,sessions,authorizeSession,moodleApi}){
  app.all("/api/sally/mcp",async(req,res)=>{
    let server,transport;
    try{
      if(req.method!=="POST")return res.status(405).json({jsonrpc:"2.0",error:{code:-32000,message:"Method not allowed"},id:null});
      server=createSallyMcpServer({actor:req.actor,sessions,authorizeSession,moodleApi});transport=new StreamableHTTPServerTransport({sessionIdGenerator:undefined});await server.connect(transport);await transport.handleRequest(req,res,req.body);
    }catch(error){if(!res.headersSent)res.status(Number(error.status||500)).json({jsonrpc:"2.0",error:{code:-32603,message:String(error.message||"MCP error")},id:null});}
    finally{res.on("close",()=>{transport?.close();server?.close();});}
  });
}

module.exports={createSallyMcpServer,registerSallyMcpRoute};
